export const EMAIL_CHANGED = "email_changed";
export const PASSWORD_CHANGED = "password_changed";
export const CONFIRM_PASSWORD_CHANGED = "confirm_password_changed";
export const NAME_CHANGED = "NAME_CHANGED";
export const LAST_NAME_CHANGED = "LAST_NAME_CHANGED";

export const FETCH_GEOFENCES_SUCCESS = "FETCH_GEOFENCES_SUCCESS";
export const FETCH_GEOFENCES_FAILURE = "FETCH_GEOFENCES_SUCCESS_FAILURE";
export const FETCH_GEOFENCES_IS_LOADING = "FETCH_GEOFENCES_IS_LOADING";
export const RESET_GEOFENCES_DATA = "RESET_GEOFENCES_DATA";

export const FECTH_SUSCRIPTIONS_SUCCESS = "FECTH_SUSCRIPTIONS_SUCCESS";
export const FETCH_SUSCRIPTIONS_FAILURE = "FETCH_SUSCRIPTIONS_FAILURE";
export const FETCH_SUSCRIPTIONS_IS_LOADING = "FETCH_SUSCRIPTIONS_IS_LOADING";
export const SUSCRIPTION_ADDED = "SUSCRIPTION_ADDED";
export const SUSCRIPTION_REMOVED = "SUSCRIPTION_REMOVED";

export const SUSCRIPTION_CREATE_SUCCESS = "SUSCRIPTION_CREATE_SUCCESS";
export const SUSCRIPTION_CREATE_ALREADY_EXISTS =
  "SUSCRIPTION_CREATE_ALREADY_EXISTS";
export const SUSCRIPTION_CREATE_FAILURE = "SUSCRIPTION_CREATE_FAILURE";
export const RESET_SUSCRIPTION_CREATE_DATA = "RESET_SUSCRIPTION_CREATE_DATA";
export const SUSCRIPTION_CREATE_IS_LOADING = "SUSCRIPTION_CREATE_IS_LOADING";

export const SIGNIN_SUCCESS = "signin_succes";
export const SIGNIN_FAILED = "signin_failed";
export const SIGNIN_IS_LOADING = "signin_loading";

export const SIGNUP_SUCCESS = "signup_succes";
export const SIGNUP_FAILED = "signup_failed";
export const SIGNUP_IS_LOADING = "signiup_loading";

export const RESET_AUTH = "reset_auth";

export const GEOTAB_SIGNUP_SUCCESS = "GEOTAB_SIGNUP_SUCCESS";
export const GEOTAB_SIGNUP_FAILED = "GEOTAB_SIGNUP_FAILED";
export const GEOTAB_SIGNUP_IS_LOADING = "GAOTAB_SIGNUP_IS_LOADING";
export const GEOTAB_RESET_AUTH_REDUCER = "GEOTAB_RESET_AUTH_REDUCER";

export const FETCH_DEVICES_INFO_SUCCESS = "FETCH_DEVICES_INFO_SUCCESS";
export const FETCH_DEVICES_INFO_FAILURE = "FETCH_DEVICES__INFO_FAILURE";

export const GET_USER_LOCATION_SUCCESS = "GET_USER_LOCATION_SUCCESS";
export const GET_USER_LOCATION_FAILURE = "GET_USER_LOCATION_FAILURE";
export const RESET_USER_LOCATION_REDUCER = "RESET_USER_LOCATION_REDUCER";
export const GET_USER_LOCATION_IS_LOADING = "GET_USER_LOCATION_IS_LOADING";

export const SUSCRIPTION_CANCELATION_SUCCESS =
  "SUSCRIPTION_CANCELATION_SUCCESS";
export const SUSCRIPTION_CANCELATION_FAILURE =
  "SUSCRIPTION_CANCELATION_FAILURE";

export const RESET_SUSCRIPTION_CANCELATION_REDUCER =
  "RESET_SUSCRIPTION_CANCELATION_REDUCER";

export const FETCH_ESPECIFIC_GEOFENCE_SUCCESS =
  "FETCH_SPECIFIC_GEOFENCE_SUCCESS";
export const FETCH_ESPECIFIC_GEOFENCE_FAILURE =
  "FETCH_SPECIFIC_GEOFENCE_FAILURE";
export const RESET_ESPECIFIC_GEOFENCE_REDUCER =
  "RESET_ESPECIFIC_GEOFENCE_REDUCER";

export const FETCH_GEOFENCE_DETAIL_SUCCES = "FETCH_GEOFENCE_DETAIL_SUCCES";
export const FETCH_GEOFENCE_DETAIL_FAILURE = "FETCH_GEOFENCE_DETAIL_FAILURE";
export const RESET_GEOFENCE_DETAIL_REDUCER = "RESET_GEOFENCE_DETAIL_REDUCER";

export const FETCH_VEHICLE_DETAIL_SUCCESS = "FETCH_VEHICLE_DETAIL_SUCCESS";
export const RESET_VEHICLE_DETAIL_REDUCER = "RESET_VEHICLE_DETAIL_REDUCER";

export const FETCH_DRIVER_DETAIL_SUCCESS = "FETCH_DRIVER_DETAIL_SUCCESS";
export const RESET_DRIVER_DETAIL_REDUCER = "RESET_DRIVER_DETAIL_REDUCER";

export const FETCH_DEVICE_STATUS_SUCCES = "FETCH_DEVICE_STATUS_SUCCES";
export const FETCH_DEVICE_STATUS_FAILURE = "FETCH_DEVICE_STATUS_FAILURE";
export const FETCH_DEVICE_STATUS_IS_LOADING = "FETCH_DEVICE_STATUS_IS_LOADING";
export const RESET_DEVICE_STATUS_REDUCER = "RESET_DEVICE_STATUS_REDUCER";

export const CHANGE_SUSCRIPTION_SUCCESS = "CHANGE_SUSCRIPTION_SUCCESS";
export const CHANGE_SUSCRIPTION_FAILURE = "CHANGE_SUSCRIPTION_FAILURE";
export const CHANGE_SUSCRIPTION_IS_LOADING = "CHANGE_SUSCRIPTION_LOADING";

export const FETCH_DRIVERS_SUCCESS = "FETCH_DRIVERS_SUCCESS";
export const FETCH_DRIVERS_FAILURE = "FETCH_DRIVERS_SUCCESS";
export const FETCH_DRIVERS_IS_LOADING = "FETCH_DRIVERS_IS_LOADING";

export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_IS_LOADING = "FETCH_VEHICLES_IS_LOADING";

export const CREATE_RATE_SUCCES = "CREATE_RATE_SUCCES";
export const CREATE_RATE_FAILURE = "CREATE_RATE_FAILURE";
export const CREATE_RATE_IS_LOADING = "CREATE_RATE_IS_LOADING";
export const RESET_CREATE_RATE_REDUCER = "RESET_CREATE_RATE_REDUCER";

export const FETCH_ALERTS_SUCCESFULL = "FETCH_ALERTS_SUCCESFULL";
export const FETCH_ALERTS_IS_LOADING = "FETCH_ALERTS_IS_LOADING";

export const FETCH_TIPS_SUCCESFULL = "FETCH_TIPS_SUCCESFULL";
export const FETCH_TIPS_IS_LOADING = "FETCH_TIPS_IS_LOADING";

//  DEVICES STATUS ACTIONS TYPES
export const FETCH_VEHICLES_STATUS_SUCCES = "FETCH_VEHICLES_STATUS_SUCCES";
export const FETCH_VEHICLES_STATUS_FAILURE = "FETCH_VEHICLES_STATUS_FAILURE";
export const FETCH_VEHICLES_STATUS_IS_LOADING =
  "FETCH_VEHICLES_STATUS_IS_LOADING";
export const RESET_VEHICLES_STATUS_REDUCER = "RESET_VEHICLES_STATUS_REDUCER";

export const ADD_SUSCRIPTION_ROLE = "ADD_SUSCRIPTION_ROLE";

export const FETCH_ROUTES_IS_LOADING = "FETCH_ROUTES_IS_LOADING";
export const FETCH_ROUTES_SUCCEEDED = "FETCH_ROUTES_SUCCEEDED";
export const FETCH_ROUTES_FAILED = "FETCH_ROUTES_FAILED";

export const FETCH_DEVICE_LOCATION_SUCCEEDED =
  "FETCH_DEVICE_LOCATION_SUCCEEDED";
export const FETCH_DEVICE_LOCATION_FAILED = "FETCH_DEVICE_LOCATION_FAILED";
export const FETCH_DEVICE_LOCATION_IS_LOADING =
  "FETCH_DEVICE_LOCATION_IS_LOADING";
