export const APPLE_BLUE_COLOR = "#007AFF";
export const LIGHT_GRAY = "#F1F1F2";
export const CANDY_RED_COLOR = "#ff0800";

export const PRESENT_VEHICLE_LOCATION_SCREEN =
  "PRESENT_VEHICLE_LOCATION_SCREEN";
export const PRESENT_SUSCRIPTION_SETTINGS_SCREEN =
  "PRESENT_SUSCRIPTION_SETTINGS_SCREEN";
export const PRESENT_COMPOSE_RATE_SCREEN = "PRESENT_COMPOSE_RATE_SCREEN";

export const VER_BLUE_COLOR = "#212f4b";

export const YELLOW_COLOR = "#EBC646";
export const BLUE_COLOR = "#68AEF0";
export const LIME_GREEN_COLOR = "#478906";
